#!/bin/sh
_profile='profile-findbugs.xml'

echo '<?xml version="1.0" encoding="UTF-8"?>' > ${_profile}
echo '<!-- generated by fb2sq -->' >> ${_profile}
echo '<FindBugsFilter>' >> ${_profile}
for i in `grep '<rule key=' rules-*.xml | cut -d '"' -f 2`; do
	echo '  <Match>' >> ${_profile}
	echo "    <Bug pattern=\"$i\"/>" >> ${_profile}
	echo '  </Match>' >> ${_profile}
done
echo '</FindBugsFilter>' >> ${_profile}
