#!/bin/sh
_profile='profile-findbugs.xml'
_sqrules='sq_rules.dat'

cd $(dirname $0)
echo '<?xml version="1.0" encoding="UTF-8"?>' > ${_profile}
echo '<!-- generated by fb2sq -->' >> ${_profile}
echo '<FindBugsFilter>' >> ${_profile}
for i in `grep '<rule key=' rules-*.xml | cut -d '"' -f 2`; do
	#echo "grep '^$i:' sq_rules.dat | grep ':DISABLED'"
	v=$(grep "^$i:" ${_sqrules} | grep -q ':DISABLED' && echo 1)
	if [ "$v" != "1" ]; then
		echo '  <Match>' >> ${_profile}
		echo "    <Bug pattern=\"$i\"/>" >> ${_profile}
		echo '  </Match>' >> ${_profile}
	fi
done
echo '</FindBugsFilter>' >> ${_profile}
